# Generated by Django 5.2 on 2026-01-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='username',
            field=models.CharField(default='Unknown', max_length=150),
        ),
    ]
