# Generated by Django 5.2 on 2026-01-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_attendance_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='employee',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='username',
            field=models.CharField(default='Unknown', max_length=150),
        ),
    ]
